platform :android do
  desc "Upload AAB to Open testing track"
  lane :upload_to_open do
    supply(
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEYS"],
      package_name: "com.livulkiluv.ilivukiskrl",
      aab: "build_output/com.livulkiluv.ilivukiskrl_2.aab",
      track: "beta", # ← вот так!
      release_status: "completed",
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end

